defaults:
  - _self_
  - train/data
  - train/model
  - api/settings
  - data/feature_cols

hydra:
  output_subdir: null                      # Don't create .hydra/ subfolder
  run:
    dir: .                                 # Stay in current directory
  job_logging:
    handlers:
      file:
        filename: logs/${hydra.job.name}.log
